# Generated by Django 2.2.5 on 2020-02-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200219_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='failities',
            new_name='facilities',
        ),
    ]
